Create FAQ Card
ilovemyteams/About-my-Team pull request #286
Opened 2024-09-06 10:24 UTC by petalser

1. Added FAQ Card (QaCard);
2. Added LikeButton;
3. Added an icon for LikeButton;
4. Added ReadTimeEst;
5. New utility that estimatesreading time (min value 1);
6. New utility that normalizes GDrive-stored image URLs;
7. Updated messages (new values, new namespace for 
        non-interactable interface elements).

2024-09-06 18:46 UTC, IraMira333 requested changes

2024-09-06 18:46 UTC, IraMira333 commented on messages/ua.json
> +        "titleFourthWord": "бізнес ",
Тут так не має бути. Поверни як було. Має бути бізнес-ідей фіолетовим.

2024-09-06 18:46 UTC, IraMira333 commented on src/components/shared/Icons/IconLike.tsx
> +        >
Бажано дописати aria-label

2024-09-06 18:50 UTC, IraMira333 commented
І закинь компонент на сторінку, щоб його можна було подивитись і потестити.

2024-09-07 19:45 UTC, OlgaMykhailova commented on src/components/shared/ReadTimeEst.tsx
> +export const ReadTimeEst = ({ text, className = "" }: ReadTimeEstProps) => {
функції повинні мати назву від дієслова, наприклад, getEstimationTime, та починатись з маленької літери

2024-09-07 19:47 UTC, OlgaMykhailova commented on src/utils/readingTimeEstimation.ts
> +    return Math.ceil(text.split(" ").length / 180);
функції мають починатися з дієслова. наприклад, getEstimationTime

2024-09-07 20:37 UTC, petalser commented on src/utils/readingTimeEstimation.ts
> +    return Math.ceil(text.split(" ").length / 180);
Виправив

2024-09-09 08:45 UTC, IraMira333 commented on src/utils/normalizeGoogleDriveImgUrls.ts
Напиши комент до функціі, що її треба буде видалити коли картинки приходитимуть з Sanity.
 //TODO: Remove the function when pictures come from Sanity

2024-09-09 09:36 UTC, OlgaMykhailova commented on src/components/qAsection/QaCard.tsx
> +                        >
зроби, будь ласка, підкреслення через border, через underline воно не відповідає макету

2024-09-09 09:49 UTC, OlgaMykhailova commented on src/components/shared/Icons/IconLike.tsx
> +            viewBox="0 0 19 17"
здається, що іконка неправильно експортована. вона має бути в розмірах 24х24, тому і маржин потім в стилях додаєш

2024-09-09 10:00 UTC, OlgaMykhailova commented on src/components/shared/LikeButton.tsx
> +        </button>
кількість лайків має бути іншим кольором

2024-09-09 10:01 UTC, OlgaMykhailova commented on src/components/qAsection/QaCard.tsx
> +                        <LikeButton likes={likes} />
немає необхідних відступів між заголовком, основним текстом, та нижнім блоком картки

2024-09-09 10:04 UTC, OlgaMykhailova commented on src/components/qAsection/QaCard.tsx
> +                        >
і треба запитати, чи має бути ховер-ефект при наведенні

2024-09-09 10:07 UTC, OlgaMykhailova commented on src/components/qAsection/QaCard.tsx
> +                />
картинка для таблета та десктопа має бути відцентрована по центру блоку по вертикалі

2024-09-12 18:45 UTC, petalser commented on src/components/qAsection/QaCard.tsx
> +                        >
Зробив  через псевдо-елемент. Якщо через бордер, то бордер виходить надто далеко від тексту

2024-09-13 08:09 UTC, OlgaMykhailova commented on src/components/shared/LikeButton.tsx
> +        </button>
сердечко та кількість лайків мають бути по вертикалі. треба прибрати паддінги та відцентрувати 
![image](https://github.com/user-attachments/assets/1094accd-0116-488b-b6da-6932c6af901d)

2024-09-13 08:13 UTC, OlgaMykhailova commented on src/components/qAsection/QaCard.tsx
> +                        {getTranslation("readMore")}
помилка в стилях, на таблеті підкреслення неправильного кольору

2024-09-13 08:17 UTC, OlgaMykhailova commented on src/app/[locale]/faq/page.tsx
> +            {ITER.map(i => (
у Section className необов'язковий проп, немає необхідності передавати його пустим рядком

2024-09-13 08:30 UTC, OlgaMykhailova commented on src/components/qAsection/QaCard.tsx
> +            <Image
для чого тут потрібен container? він не дає тягнутися картці

2024-09-13 08:33 UTC, OlgaMykhailova commented on src/components/shared/Icons/IconLike.tsx
> +        >
все ж таки треба вказати іконці aria-label

2024-09-13 08:39 UTC, OlgaMykhailova commented on src/components/shared/ReadTimeEst.tsx
> +    const readTime = rte(text);
все ж таки треба чітко вказати назву компонента, якщо це лічильник прогнозованого часу, то має бути слово Counter, бо назва EstimatedReadingTime не дає чіткого уявлення, що саме це за компонент

2024-09-13 14:41 UTC, petalser commented on src/components/shared/LikeButton.tsx
> +        </button>
В макеті цифра зміщена вниз (якщо згори відстань до краю буде 54пкс, то знизу буде 52). Чи можемо ми це проігнорувати? В такому випадку буде 53 і там, і там

2024-09-13 14:55 UTC, petalser commented on src/components/qAsection/QaCard.tsx
> +                        {getTranslation("readMore")}
Там текст неправильного кольору, а підкреслення по макету. Дякую, виправив

2024-09-13 14:56 UTC, petalser commented on src/app/[locale]/faq/page.tsx
> +            {ITER.map(i => (
✔

2024-09-13 14:57 UTC, petalser commented on src/components/qAsection/QaCard.tsx
> +                    {answerText}
✔

2024-09-15 21:20 UTC, petalser commented on src/components/shared/Icons/IconLike.tsx
> +        >
Додав, але думаю, що це зайве. Ось чому:
ARIA labels are attributes that can be added to **HTML elements** to provide additional **information about the element's purpose** and functionality to assistive technologies, such as screen readers

2024-09-16 08:08 UTC, OlgaMykhailova commented on src/components/shared/Icons/IconLike.tsx
> +        >
<svg> і є html тегом для графічного контенту, якщо використати іконку тільки як зображення, а не огорнути в кнопку, без aria-label скрін рідер ніяк не дізнається, що там. тому у всіх svg aria-label має бути завжди.

2024-09-16 08:22 UTC, OlgaMykhailova commented
стягни собі Аніни зміни з dev, там інша структура папок, для сторінки FAQ в components є окрема папка, туди треба перенести картку.

2024-09-16 08:23 UTC, OlgaMykhailova commented on src/app/[locale]/faq/page.tsx
> +            {ITER.map(i => (
для списка карток треба зробити окремий компонент - qaCardList, і там мепнути всі картки.

2024-09-16 08:25 UTC, OlgaMykhailova commented on src/components/qAsection/QaCard.tsx
> +            <Image
в тебе зараз у останньої картки в списку, зайвий маржин. я рекомендую qaCardList зробити флексом і задати потрібний gap, а ці маржини прибрати.

2024-09-16 08:31 UTC, OlgaMykhailova commented on src/components/qAsection/QaCard.tsx
> +            <Image
і в мене все ж питання по контейнеру, він тут зайвий.

2024-09-17 18:42 UTC, petalser commented on src/app/[locale]/faq/page.tsx
> +            {ITER.map(i => (
✔

2024-09-17 18:44 UTC, petalser commented on src/components/qAsection/QaCard.tsx
> +            <Image
Контейнер прибрав (він там був, щоб картка не тягнулася), марджини прибрав, флекс з гепом додав

2024-09-17 18:49 UTC, petalser commented on src/components/shared/Icons/IconLike.tsx
> +        >
_якщо використати іконку тільки як зображення_, то додавати лейбл мав би той, хто використовуватиме іконку окремо. Наразі це зайва інформація (озвучена вголос).
Так чи інакше, виправив

2024-09-18 08:40 UTC, OlgaMykhailova commented on src/components/shared/Icons/IconLike.tsx
> +        >
в нас це спільний компонент, в якому вже описана вся необхідна інформація для іконки. який сенс передавати кожного разу окремий aria-label?

2024-09-19 18:02 UTC, OlgaMykhailova commented on src/components/faqPage/qaSection/QaCard.tsx
> +                    >
на підкреслення при ховері.фокусі немає транзішена

2024-09-19 18:05 UTC, OlgaMykhailova commented on src/components/faqPage/qaSection/QaCard.tsx
> +            <Image
у картки залишився зайвий маржин

2024-09-19 18:13 UTC, OlgaMykhailova commented on src/components/faqPage/qaSection/QaCard.tsx
> +            <div className="flex flex-col">
треба додати лівий та правий паддінги

2024-09-24 09:23 UTC, IraMira333 requested changes

2024-09-24 09:25 UTC, IraMira333 commented on src/components/faqPage/qaSection/QaCardList.tsx
> +    return (
Тільки ж маю на увазі огорнути треба весь компонент QaCardList, а не тільки те що виділено в коменті.

2024-09-24 10:46 UTC, IraMira333 approved these changes

2024-09-24 10:51 UTC, merged