Task 63/create footer structure
ilovemyteams/About-my-Team pull request #29
Opened 2024-03-12 12:56 UTC by NataPas2021

![footer pc](https://github.com/ilovemyteams/About-my-Team/assets/94239256/c21aadb5-7d66-4afb-86e1-31a2a3c780a2)

footer for pc

2024-03-12 13:13 UTC, OlenaPosternak requested changes

2024-03-12 13:13 UTC, OlenaPosternak commented on src/components/footerSection/FooterSection.tsx
> +            <Section id="footer">
Нам потрібен цей франгмент?

2024-03-12 13:13 UTC, OlenaPosternak commented on src/components/footerSection/Copyright.tsx
> +
Можна використати HTML symdols

2024-03-12 13:13 UTC, OlenaPosternak commented on src/components/footerSection/FooterSection.tsx
> +                        <BuyMeCoffeeLink className="w-[48px] h-[48px] mr-[105px]" />
Кава і в Хіроу 48 стала. Заміни будь ласка в компоненті цей розмір, а тут прибери. Дякую.

2024-03-12 13:13 UTC, OlenaPosternak commented on src/components/footerSection/FooterSection.tsx
> +                <div className="flex mt-[18.5px] justify-between">
Цей марджин має вплив? У тебе є відступ від заголовку вниз.

2024-03-12 13:13 UTC, OlenaPosternak commented on src/components/footerSection/MenuFooter.tsx
> +        <>
нам потрібен цей фрагмент?

2024-03-12 13:13 UTC, OlenaPosternak commented on src/components/footerSection/PrivacyPolicy.tsx
> +        <>
НАм потрібен цей фрагмент?

2024-03-12 13:17 UTC, NataPas2021 commented on src/components/footerSection/FooterSection.tsx
> +            <Section id="footer">
прибрала)

2024-03-12 13:18 UTC, NataPas2021 commented on src/components/footerSection/FooterSection.tsx
> +                        <BuyMeCoffeeLink className="w-[48px] h-[48px] mr-[105px]" />
зробила)

2024-03-12 13:19 UTC, NataPas2021 commented on src/components/footerSection/MenuFooter.tsx
> +import Link from "next/link";
що першим поставити?

2024-03-12 13:21 UTC, NataPas2021 commented on src/components/footerSection/MenuFooter.tsx
> +            <ul className="flex flex-start mr-[236px] font-geist text-base [&>*:last-child]:mr-0 ">
там проблема в тому, що коли я їх розсуваю, то вони не стають саме так, як на макеті. тому і довелося марджин задавати

2024-03-12 13:21 UTC, NataPas2021 commented on src/components/footerSection/PrivacyPolicy.tsx
> +        <>
видалила)

2024-03-12 13:21 UTC, NataPas2021 commented on src/components/footerSection/MenuFooter.tsx
> +        <>
видалила)

2024-03-12 13:23 UTC, NataPas2021 commented on src/components/footerSection/FooterSection.tsx
> +                <div className="flex mt-[18.5px] justify-between">
так, має. бо це відступ від лінії

2024-03-12 13:38 UTC, NataPas2021 commented on src/components/footerSection/Copyright.tsx
> +
done)

2024-03-12 13:52 UTC, OlenaPosternak commented on src/components/footerSection/MenuFooter.tsx
> +import Link from "next/link";
Link. саме під ним я лишила коментар.

2024-03-12 13:54 UTC, OlenaPosternak commented on src/components/footerSection/MenuFooter.tsx
> +            <ul className="flex flex-start mr-[236px] font-geist text-base [&>*:last-child]:mr-0 ">
Якщо Каву і подлитись огорнути в дів і розсунути по краям флекс контейнера, то вірогідно необхідність марджину зникне.

2024-03-12 15:15 UTC, NataPas2021 commented on src/components/footerSection/MenuFooter.tsx
> +        <ul className="flex flex-start mr-[236px] font-geist text-base [&>*:last-child]:mr-0 ">
ok

2024-03-12 15:17 UTC, NataPas2021 commented on src/components/footerSection/MenuFooter.tsx
> +            <ul className="flex flex-start mr-[236px] font-geist text-base [&>*:last-child]:mr-0 ">
я його огортала, але воно не ставало саме так, як на макеті

2024-03-12 20:28 UTC, OlgaMykhailova commented on src/components/shared/ButtonShare.tsx
>          >
кнопка на макеті шрифтом caviar 
![image](https://github.com/ilovemyteams/About-my-Team/assets/100313107/1c93b415-9aa8-4e00-97bb-bff55436b41a)

2024-03-12 20:32 UTC, OlgaMykhailova commented on src/app/[locale]/page.tsx
> +            <FooterSection />
футер повинен жити в layout, після main. краще дати назву Footer без слова section

2024-03-12 20:33 UTC, OlgaMykhailova commented on src/components/footerSection/Copyright.tsx
> +};
правильна назва copyright

2024-03-12 20:49 UTC, NataPas2021 commented on src/components/footerSection/Copyright.tsx
> +};
ок)

2024-03-12 21:00 UTC, NataPas2021 commented on src/app/[locale]/page.tsx
> +            <FooterSection />
шось я його поклала в лейаут і тепер він взагалі не відображається

2024-03-12 21:03 UTC, NataPas2021 commented on src/components/shared/ButtonShare.tsx
>          >
ok)

2024-03-12 21:12 UTC, OlgaMykhailova commented on src/components/footerSection/Copyright.tsx
> +};
назву компоненту теж треба змінити

2024-03-12 21:20 UTC, OlgaMykhailova commented on src/components/footerSection/Copyright.tsx
> +};
![image](https://github.com/ilovemyteams/About-my-Team/assets/100313107/8fea5d40-e9bb-404c-8a3c-26eaad8bf670)

2024-03-12 21:25 UTC, NataPas2021 commented on src/components/footerSection/Copyright.tsx
> +};
так я ж змінила)

2024-03-13 14:03 UTC, IraMira333 approved these changes

2024-03-13 14:23 UTC, OlgaMykhailova commented on src/app/[locale]/layout.tsx
перемісти, будь ласка, імпорт футера вище імпорта globals.css, стилі завжди останніми імпортуються

2024-03-13 14:35 UTC, NataPas2021 commented on src/app/[locale]/layout.tsx
done

2024-03-13 14:35 UTC, merged