Added data for question8
ilovemyteams/About-my-Team pull request #446
Opened 2024-11-13 21:37 UTC by petalser

2024-11-13 21:49 UTC, IraMira333 requested changes

2024-11-13 21:49 UTC, IraMira333 commented on src/mockedData/questionsData.ts
> +                            title: "Терміни та ціни виконання лендінгу можуть варіюватися залежно від складності проєкту, вимог замовника та особливостей дизайну й функціоналу. У середньому, на створ
Деякі речення, згідно макету, мають бути з нового рядка.

2024-11-14 09:49 UTC, AnnaPrutnik commented on src/mockedData/questionsData.ts
> +                            title: "Терміни та ціни виконання лендінгу можуть варіюватися залежно від складності проєкту, вимог замовника та особливостей дизайну й функціоналу. У середньому, на створ
виправлено

2024-11-14 11:19 UTC, AnnaPrutnik approved these changes

2024-11-14 13:41 UTC, IraMira333 approved these changes

2024-11-14 13:41 UTC, merged