commit to task
ilovemyteams/About-my-Team pull request #8
Opened 2024-03-05 19:47 UTC by NataPas2021

![task 145](https://github.com/ilovemyteams/About-my-Team/assets/94239256/6ee3263a-86b5-4936-adea-b1a8d49dfb54)

2024-03-05 20:50 UTC, OlenaPosternak requested changes

2024-03-05 20:50 UTC, OlenaPosternak commented on src/components/sectionQA/Accordion.tsx
> +                    <svg className="w-4 h-4 pc:min-w-6 pc:h-6 bg-purple-100"></svg>
Маємо вже дизайн іконок, краще одразу використати

2024-03-05 20:50 UTC, OlenaPosternak commented on src/components/sectionQA/Accordion.tsx
> +                className={`grid overflow-hidden transition-all duration-300 ease-in-out text-sm
тут треба нам всім домовитись напевно про один duration і тип транзішина. Що думаєш? 
Також зазвичай transition all пагано впиває на сайт, можуть бути трабли, через неочікувану поведінку цієї властивості і використовувати її краще у крайньому випадку. А можеш спробувати чи буде працювати transition-[overflow] наприклад?

2024-03-05 20:50 UTC, OlenaPosternak commented on src/components/shared/ButtonShare.tsx
> +            className={`float-right h-[25px] justify-end items-end my-[8px] underline ${className}`}
якщо це спільна кнопка, то стилі які поза боксом, такі як марджин, краще з неї прибрати. Бо у якомусь компонеті він не знадобиться. Тільки коли ми впевнені на 100% що у всіх однаково по сайту і нам підійде цей відступ

2024-03-05 20:50 UTC, OlenaPosternak commented on src/components/sectionQA/QuestionsList.tsx
> +        <div className="block ml-[270px] mb-[32px]">
А для чого використовуємо тут block  ?

2024-03-05 22:42 UTC, NataPas2021 commented on src/components/sectionQA/Accordion.tsx
> +                    <svg className="w-4 h-4 pc:min-w-6 pc:h-6 bg-purple-100"></svg>
обовязково)) у наступному пр))

2024-03-05 22:43 UTC, NataPas2021 commented on src/components/sectionQA/Accordion.tsx
> +                className={`grid overflow-hidden transition-all duration-300 ease-in-out text-sm
я тільки за)) скажіть які дюрейшини траншіщини ставити і я то зроблю))

2024-03-05 22:44 UTC, NataPas2021 commented on src/components/sectionQA/QuestionsList.tsx
> +        <div className="block ml-[270px] mb-[32px]">
прибрала))

2024-03-07 09:10 UTC, NataPas2021 commented
new build

2024-03-07 09:10 UTC, closed without merging